CREATE TABLE IF NOT EXISTS "crm_weekly_reports" (
  "id" varchar PRIMARY KEY DEFAULT gen_random_uuid(),
  "week_start" date NOT NULL,
  "week_end" date NOT NULL,
  "title" text NOT NULL,
  "status" text NOT NULL DEFAULT 'draft',
  "prepared_by" varchar NOT NULL REFERENCES "users"("id"),
  "recipient_name" text,
  "recipient_role" text,
  "new_leads_added" integer DEFAULT 0,
  "leads_worked" integer DEFAULT 0,
  "outreach_emails_sent" integer DEFAULT 0,
  "follow_ups_sent" integer DEFAULT 0,
  "calls_completed" integer DEFAULT 0,
  "meetings_booked" integer DEFAULT 0,
  "proposals_sent" integer DEFAULT 0,
  "deals_advanced" integer DEFAULT 0,
  "closed_won_count" integer DEFAULT 0,
  "estimated_pipeline_value" numeric(10, 2),
  "executive_summary" text,
  "wins" text,
  "pipeline_updates" text,
  "blockers" text,
  "next_week_focus" text,
  "support_needed" text,
  "created_at" timestamp DEFAULT now(),
  "updated_at" timestamp DEFAULT now()
);
