import { useMemo, useState } from "react";
import { Link } from "wouter";
import { useMutation, useQuery } from "@tanstack/react-query";
import { ArrowLeft, Copy, Eye, FileText, Pencil, Plus, Trash2, Video } from "lucide-react";
import { BriefingEditor } from "@/components/aviation-briefings/BriefingEditor";
import type { AviationBriefing } from "@/components/aviation-briefings/types";
import { aviationBriefingInputSchema, type AviationBriefingInput } from "@shared/config/aviationBriefings";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { useAuth } from "@/hooks/useAuth";
import { useToast } from "@/hooks/use-toast";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { apiUrl } from "@/lib/api";

const emptyBriefing: AviationBriefingInput = { title: "", slug: "", excerpt: "", contentType: "article", category: "Flight Planning", status: "draft", isFeatured: false, featuredImageUrl: "", featuredImageStorageKey: "", featuredImageAlt: "", featuredImageCredit: "", featuredImageCreditUrl: "", articleContent: [{ type: "paragraph", text: "" }], videoSourceType: null, videoUrl: "", videoStorageKey: "", videoThumbnailUrl: "", videoDurationSeconds: null, videoTranscript: "", supportingContent: [], contributors: [], relevantToolIds: [], seoTitle: "", seoDescription: "", publishedAt: null, scheduledAt: null };

function toInput(item: AviationBriefing): AviationBriefingInput { return { ...emptyBriefing, title: item.title, slug: item.slug, excerpt: item.excerpt, contentType: item.contentType, category: item.category, status: item.status as AviationBriefingInput["status"], isFeatured: item.isFeatured, featuredImageUrl: item.featuredImageUrl || "", featuredImageStorageKey: item.featuredImageStorageKey || "", featuredImageAlt: item.featuredImageAlt || "", featuredImageCredit: item.featuredImageCredit || "", featuredImageCreditUrl: item.featuredImageCreditUrl || "", articleContent: item.articleContent || [], videoSourceType: item.videoSourceType || null, videoUrl: item.videoUrl || "", videoStorageKey: item.videoStorageKey || "", videoThumbnailUrl: item.videoThumbnailUrl || "", videoDurationSeconds: item.videoDurationSeconds || null, videoTranscript: item.videoTranscript || "", supportingContent: item.supportingContent || [], contributors: item.contributors || [], relevantToolIds: item.relevantToolIds || [], seoTitle: item.seoTitle || "", seoDescription: item.seoDescription || "", publishedAt: item.publishedAt || null, scheduledAt: item.scheduledAt || null }; }

function briefingValidationMessage(value: AviationBriefingInput) {
  const parsed = aviationBriefingInputSchema.safeParse(value);
  if (parsed.success) return "";
  return parsed.error.issues.map((issue) => `${issue.path.length ? issue.path.join(" → ") + ": " : ""}${issue.message}`).join(" ");
}

async function fetchAdminJson(path: string) {
  const response = await fetch(apiUrl(path), { credentials: "include" });
  if (!response.ok) {
    const payload = await response.json().catch(() => null);
    throw new Error(payload?.error || "Unable to load Aviation Briefings administration data.");
  }
  return response.json();
}

export default function AdminAviationBriefingsPage() {
  const { user, isLoading: authLoading } = useAuth();
  const { toast } = useToast();
  const [search, setSearch] = useState("");
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form, setForm] = useState<AviationBriefingInput>(emptyBriefing);
  const [saveError, setSaveError] = useState("");
  const [inviteForm, setInviteForm] = useState({ contributorName: "", contributorEmail: "", organization: "", internalNote: "", expiresAt: "" });
  const [lastInviteUrl, setLastInviteUrl] = useState("");
  const { data, isLoading } = useQuery<{ briefings: AviationBriefing[]; total: number; summaryRows: Array<{ status: string; contentType: string; featured: boolean; count: number }> }>({ queryKey: ["/api/admin/aviation-briefings"], queryFn: () => fetchAdminJson("/api/admin/aviation-briefings"), enabled: Boolean(user?.isSuperAdmin) });
  const { data: inviteData } = useQuery<any>({ queryKey: ["/api/admin/aviation-briefing-invitations"], queryFn: () => fetchAdminJson("/api/admin/aviation-briefing-invitations"), enabled: Boolean(user?.isSuperAdmin) });
  const { data: submissionData } = useQuery<any>({ queryKey: ["/api/admin/aviation-briefing-submissions"], queryFn: () => fetchAdminJson("/api/admin/aviation-briefing-submissions"), enabled: Boolean(user?.isSuperAdmin) });
  const { data: engagementData } = useQuery<any>({ queryKey: ["/api/admin/aviation-briefings/engagement-analytics"], queryFn: () => fetchAdminJson("/api/admin/aviation-briefings/engagement-analytics"), enabled: Boolean(user?.isSuperAdmin) });
  const { data: suggestionData } = useQuery<any>({ queryKey: ["/api/admin/aviation-briefing-suggestions"], queryFn: () => fetchAdminJson("/api/admin/aviation-briefing-suggestions"), enabled: Boolean(user?.isSuperAdmin) });
  const createInvite = useMutation({ mutationFn: async () => { const response = await apiRequest("POST", "/api/admin/aviation-briefing-invitations", { ...inviteForm, expiresAt: inviteForm.expiresAt ? new Date(inviteForm.expiresAt).toISOString() : null }); return response.json(); }, onSuccess: (payload) => { setLastInviteUrl(payload.submissionUrl); setInviteForm({ contributorName: "", contributorEmail: "", organization: "", internalNote: "", expiresAt: "" }); queryClient.invalidateQueries({ queryKey: ["/api/admin/aviation-briefing-invitations"] }); } });
  const inviteAction = useMutation({ mutationFn: async ({ id, action }: { id: string; action: string }) => { const response = await apiRequest("POST", `/api/admin/aviation-briefing-invitations/${id}/${action}`); return response.json(); }, onSuccess: (payload) => { if (payload.submissionUrl) setLastInviteUrl(payload.submissionUrl); queryClient.invalidateQueries({ queryKey: ["/api/admin/aviation-briefing-invitations"] }); } });
  const reviewAction = useMutation({ mutationFn: ({ id, action, message }: { id: string; action: string; message?: string }) => apiRequest("POST", `/api/admin/aviation-briefing-submissions/${id}/${action}`, { message }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["/api/admin/aviation-briefing-submissions"] }) });
  const reviewUpdate = useMutation({ mutationFn: ({ id, updates }: { id: string; updates: Record<string, unknown> }) => apiRequest("PATCH", `/api/admin/aviation-briefing-submissions/${id}`, updates), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["/api/admin/aviation-briefing-submissions"] }) });
  const convertSubmission = useMutation({ mutationFn: async (id: string) => { const response = await apiRequest("POST", `/api/admin/aviation-briefing-submissions/${id}/convert-to-briefing`); return response.json(); }, onSuccess: () => { toast({ title: "Converted to an unpublished briefing draft" }); queryClient.invalidateQueries({ queryKey: ["/api/admin/aviation-briefing-submissions"] }); queryClient.invalidateQueries({ queryKey: ["/api/admin/aviation-briefings"] }); } });
  const suggestionAction = useMutation({ mutationFn: ({ id, method, body }: { id: string; method: "PATCH" | "DELETE"; body?: any }) => apiRequest(method, `/api/admin/aviation-briefing-suggestions/${id}`, body), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["/api/admin/aviation-briefing-suggestions"] }) });
  const convertSuggestion = useMutation({ mutationFn: async (id: string) => { const response = await apiRequest("POST", `/api/admin/aviation-briefing-suggestions/${id}/convert-to-invitation`); return response.json(); }, onSuccess: (payload) => { setLastInviteUrl(payload.submissionUrl); toast({ title: "Contributor invitation created", description: "The secure link is ready to copy above." }); queryClient.invalidateQueries({ queryKey: ["/api/admin/aviation-briefing-suggestions"] }); queryClient.invalidateQueries({ queryKey: ["/api/admin/aviation-briefing-invitations"] }); } });
  const save = useMutation({ mutationFn: async () => { setSaveError(""); const localError = briefingValidationMessage(form); if (localError) throw new Error(localError); const isExisting = Boolean(editingId && editingId !== "new"); const response = await apiRequest(isExisting ? "PATCH" : "POST", isExisting ? `/api/admin/aviation-briefings/${editingId}` : "/api/admin/aviation-briefings", form); return response.json(); }, onSuccess: (payload) => { const saved = payload.briefing as AviationBriefing; setSaveError(""); toast({ title: payload.recoveredExisting ? "Existing briefing reopened" : "Briefing saved", description: payload.recoveredExisting ? "The first save had already created this briefing. It is now open for editing and publishing." : "Your briefing remains open so you can continue editing, previewing, or publishing it." }); setEditingId(saved.id); setForm(toInput(saved)); queryClient.invalidateQueries({ queryKey: ["/api/admin/aviation-briefings"] }); }, onError: (error: Error) => { setSaveError(error.message); toast({ title: "Unable to save briefing", description: error.message, variant: "destructive" }); } });
  const action = useMutation({ mutationFn: ({ id, action }: { id: string; action: string }) => apiRequest("POST", `/api/admin/aviation-briefings/${id}/${action}`), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["/api/admin/aviation-briefings"] }) });
  const remove = useMutation({ mutationFn: (id: string) => apiRequest("DELETE", `/api/admin/aviation-briefings/${id}`), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["/api/admin/aviation-briefings"] }) });
  const filtered = (data?.briefings || []).filter((item) => `${item.title} ${item.slug} ${item.excerpt}`.toLowerCase().includes(search.toLowerCase()));
  const totals = useMemo(() => { const rows = data?.summaryRows || []; return { total: rows.reduce((sum, row) => sum + row.count, 0), published: rows.filter((r) => r.status === "published").reduce((s, r) => s + r.count, 0), drafts: rows.filter((r) => r.status === "draft").reduce((s, r) => s + r.count, 0), review: rows.filter((r) => r.status === "review").reduce((s, r) => s + r.count, 0), videos: rows.filter((r) => r.contentType === "video").reduce((s, r) => s + r.count, 0) }; }, [data]);
  const showBriefingLibrary = () => { setEditingId(null); setForm(emptyBriefing); setSaveError(""); window.setTimeout(() => document.getElementById("briefing-library")?.scrollIntoView({ behavior: "smooth", block: "start" }), 0); };
  if (authLoading) return <div className="min-h-screen bg-[#07101c] p-10 text-white">Loading…</div>;
  if (!user?.isSuperAdmin) return <div className="min-h-screen bg-[#07101c] p-10 text-white">Super Admin access is required.</div>;
  return <main className="min-h-screen bg-[#07101c] px-5 py-10 text-[#edf5ff] sm:px-8"><div className="mx-auto max-w-7xl"><Link href="/admin" className="inline-flex items-center text-sm text-[#8dbbfa]"><ArrowLeft className="mr-2 h-4 w-4" />Admin Dashboard</Link><div className="mt-5 flex flex-wrap items-end justify-between gap-4"><div><div className="text-sm font-bold uppercase tracking-[.2em] text-[#87b8f7]">Publishing</div><h1 className="mt-2 text-4xl font-black">Aviation Briefings</h1><p className="mt-2 text-[#aebdce]">Prepare, review, schedule, and publish RSF aviation content.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={showBriefingLibrary}><FileText className="mr-2 h-4 w-4" />Saved briefings ({data?.total || 0})</Button><Button onClick={() => { setEditingId("new"); setForm({ ...emptyBriefing }); }} className="bg-[#347edc] text-white"><Plus className="mr-2 h-4 w-4" />New briefing</Button></div></div>
  {editingId ? <section className="mt-8 rounded-2xl border border-[#526d94]/40 bg-[#0c1624] p-5 sm:p-8"><div className="mb-7 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-bold">{editingId === "new" ? "Create briefing" : "Edit briefing"}</h2>{editingId !== "new" && <p className="mt-1 text-sm text-[#9fb0c4]">Saved briefing · Continue editing or change its status when ready.</p>}</div><div className="flex flex-wrap gap-2">{editingId !== "new" && <Button asChild variant="outline"><a href={`/aviation-briefings/preview/${editingId}`} target="_blank" rel="noreferrer"><Eye className="mr-2 h-4 w-4" />Preview</a></Button>}<Button variant="outline" onClick={showBriefingLibrary}>{editingId === "new" ? "Cancel" : "Back to saved briefings"}</Button></div></div>{saveError && <div role="alert" className="mb-6 rounded-lg border border-red-400/60 bg-red-950/50 p-4 text-red-100"><div className="font-bold">This briefing could not be saved</div><p className="mt-1 text-sm leading-6">{saveError}</p></div>}<BriefingEditor value={form} onChange={(next) => { setForm(next); if (saveError) setSaveError(""); }} onSave={() => save.mutate()} saving={save.isPending} /></section> : <><section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{Object.entries(totals).map(([label, value]) => <div key={label} className="rounded-xl border border-[#526d94]/40 bg-[#0d1827] p-5"><div className="text-sm capitalize text-[#9fb0c4]">{label}</div><div className="mt-2 text-3xl font-bold">{value}</div></div>)}</section>
  <section className="mt-8 rounded-xl border border-[#526d94]/40 bg-[#0c1624] p-5"><h2 className="text-2xl font-bold">Contributor invitations</h2><div className="mt-4 grid gap-3 md:grid-cols-5"><Input placeholder="Contributor name" value={inviteForm.contributorName} onChange={e=>setInviteForm({...inviteForm,contributorName:e.target.value})}/><Input type="email" placeholder="Email" value={inviteForm.contributorEmail} onChange={e=>setInviteForm({...inviteForm,contributorEmail:e.target.value})}/><Input placeholder="Organization" value={inviteForm.organization} onChange={e=>setInviteForm({...inviteForm,organization:e.target.value})}/><Input type="datetime-local" value={inviteForm.expiresAt} onChange={e=>setInviteForm({...inviteForm,expiresAt:e.target.value})}/><Button onClick={()=>createInvite.mutate()} disabled={!inviteForm.contributorName||!inviteForm.contributorEmail}>Create secure invitation</Button></div>{lastInviteUrl&&<div className="mt-4 flex gap-2 rounded-lg bg-[#13233a] p-3"><code className="min-w-0 flex-1 truncate">{lastInviteUrl}</code><Button size="sm" onClick={()=>navigator.clipboard.writeText(lastInviteUrl)}><Copy className="mr-1 h-4 w-4"/>Copy</Button></div>}<div className="mt-4 space-y-2">{(inviteData?.invitations||[]).map((invite:any)=><div key={invite.id} className="flex flex-wrap items-center justify-between gap-3 border-t border-[#526d94]/30 pt-3"><div><b>{invite.contributorName}</b> · {invite.organization||"Independent"}<div className="text-xs text-[#9fb0c4]">{invite.status} · {invite.openedAt?"opened":"not opened"} · {invite.firstSubmissionAt?"submission created":"no submission"}</div></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>inviteAction.mutate({id:invite.id,action:"regenerate"})}>Regenerate</Button>{invite.status==="active"&&<Button size="sm" variant="destructive" onClick={()=>window.confirm("Revoke this contributor invitation?")&&inviteAction.mutate({id:invite.id,action:"revoke"})}>Revoke</Button>}</div></div>)}</div></section>
  <section className="mt-8 rounded-xl border border-[#526d94]/40 bg-[#0c1624] p-5"><h2 className="text-2xl font-bold">Editorial review queue</h2><div className="mt-4 space-y-4">{(submissionData?.submissions||[]).length===0?<p className="text-[#9fb0c4]">No contributor submissions yet.</p>:(submissionData.submissions||[]).map((s:any)=><div key={s.id} className="rounded-lg border border-[#526d94]/35 p-4"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="text-lg font-bold">{s.title}</h3><p className="text-sm text-[#aebdce]">{s.contributorName} · {s.contributorCredentials||"No credentials entered"} · {s.category}</p><a className="text-sm text-[#8dbbfa] underline" href={s.videoUrl} target="_blank" rel="noreferrer">Preview {s.videoProvider} video</a></div><Badge>{s.status.replaceAll("_"," ")}</Badge></div><div className="mt-3 grid gap-2 text-sm md:grid-cols-3"><div>Agreement: {s.agreementAccepted?"accepted":"not accepted"}</div><div>Sponsored: {s.disclosuresJson?.isSponsored?`yes — ${s.disclosuresJson.sponsorName}`:"no"}</div><div>Affiliate: {s.disclosuresJson?.hasAffiliateRelationship?"yes":"no"}</div></div><div className="mt-3 flex flex-wrap gap-4 rounded bg-[#111e30] p-3 text-sm"><label className="flex gap-2"><Checkbox checked={s.credentialsReviewed} onCheckedChange={v=>reviewUpdate.mutate({id:s.id,updates:{credentialsReviewed:v===true}})}/>Credentials reviewed</label><label className="flex gap-2"><Checkbox checked={s.aviationReviewRecommended} onCheckedChange={v=>reviewUpdate.mutate({id:s.id,updates:{aviationReviewRecommended:v===true}})}/>Additional aviation review recommended</label><label className="flex gap-2"><Checkbox checked={s.aviationReviewCompleted} onCheckedChange={v=>reviewUpdate.mutate({id:s.id,updates:{aviationReviewCompleted:v===true}})}/>Aviation review completed</label></div><div className="mt-4 flex flex-wrap gap-2">{s.status==="submitted"&&<Button size="sm" onClick={()=>reviewAction.mutate({id:s.id,action:"under-review"})}>Start review</Button>}{["submitted","under_review"].includes(s.status)&&<Button size="sm" variant="outline" onClick={()=>{const message=window.prompt("Revision request shown to contributor:");if(message)reviewAction.mutate({id:s.id,action:"request-revision",message})}}>Request revisions</Button>}{s.status==="under_review"&&<><Button size="sm" onClick={()=>reviewAction.mutate({id:s.id,action:"approve"})}>Approve</Button><Button size="sm" variant="destructive" onClick={()=>window.confirm("Reject this submission?")&&reviewAction.mutate({id:s.id,action:"reject"})}>Reject</Button></>}{s.status==="approved"&&!s.publishedBriefingId&&<Button size="sm" onClick={()=>convertSubmission.mutate(s.id)}>Convert to briefing draft</Button>}{s.publishedBriefingId&&<Badge variant="outline">Converted to draft</Badge>}</div></div>)}</div></section>
  <section className="mt-8 rounded-xl border border-[#526d94]/40 bg-[#0c1624] p-5"><h2 className="text-2xl font-bold">Private reader engagement</h2><p className="mt-1 text-sm text-[#9fb0c4]">Editorial signals only. Nothing in this section is shown publicly or used to rank contributors.</p><div className="mt-4 grid gap-3 sm:grid-cols-4"><div className="rounded bg-[#111e30] p-4"><div className="text-xs text-[#9fb0c4]">Helpful responses</div><b className="text-2xl">{(engagementData?.feedback||[]).filter((x:any)=>x.responseType==="helpful").reduce((n:number,x:any)=>n+x.count,0)}</b></div><div className="rounded bg-[#111e30] p-4"><div className="text-xs text-[#9fb0c4]">Learn-more requests</div><b className="text-2xl">{(engagementData?.feedback||[]).filter((x:any)=>x.responseType==="learn_more").reduce((n:number,x:any)=>n+x.count,0)}</b></div><div className="rounded bg-[#111e30] p-4"><div className="text-xs text-[#9fb0c4]">Saved briefings</div><b className="text-2xl">{(engagementData?.saves||[]).reduce((n:number,x:any)=>n+x.count,0)}</b></div><div className="rounded bg-[#111e30] p-4"><div className="text-xs text-[#9fb0c4]">Share actions</div><b className="text-2xl">{engagementData?.shareActions||0}</b></div></div><div className="mt-5 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-[#9fb0c4]"><th className="p-2">Briefing</th><th>Category</th><th>Helpful</th><th>Learn more</th><th>Saves</th></tr></thead><tbody>{Array.from(new Set((engagementData?.feedback||[]).map((x:any)=>x.briefingId))).map((id:any)=>{const rows=(engagementData.feedback||[]).filter((x:any)=>x.briefingId===id),first=rows[0],saved=(engagementData.saves||[]).find((x:any)=>x.briefingId===id);return <tr key={id} className="border-t border-[#526d94]/30"><td className="p-2">{first.title}</td><td>{first.category}</td><td>{rows.find((x:any)=>x.responseType==="helpful")?.count||0}</td><td>{rows.find((x:any)=>x.responseType==="learn_more")?.count||0}</td><td>{saved?.count||0}</td></tr>})}</tbody></table></div></section>
  <section className="mt-8 rounded-xl border border-[#526d94]/40 bg-[#0c1624] p-5"><h2 className="text-2xl font-bold">Future Briefing Suggestions</h2><div className="mt-4 space-y-3">{(suggestionData?.suggestions||[]).length===0?<p className="text-[#9fb0c4]">No suggestions yet.</p>:(suggestionData.suggestions||[]).map((s:any)=><div key={s.id} className="rounded-lg border border-[#526d94]/35 p-4"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-bold">{s.topic}</h3><p className="text-sm text-[#aebdce]">Suggested: {s.suggestedPerson}{s.organization?` · ${s.organization}`:""}</p><p className="mt-2 text-sm">{s.reason}</p></div><select className="h-9 rounded border border-[#607895] bg-[#0b1624] px-2" value={s.status} onChange={e=>suggestionAction.mutate({id:s.id,method:"PATCH",body:{status:e.target.value}})}>{["new","reviewing","contacted","completed","closed"].map(x=><option key={x} value={x}>{x}</option>)}</select></div><div className="mt-3 flex flex-wrap gap-2">{!s.convertedInvitationId&&<Button size="sm" onClick={()=>convertSuggestion.mutate(s.id)}>Convert to contributor invitation</Button>}{s.convertedInvitationId&&<Badge variant="outline">Invitation created</Badge>}<Button size="sm" variant="destructive" onClick={()=>window.confirm("Delete this suggestion as spam?")&&suggestionAction.mutate({id:s.id,method:"DELETE"})}>Delete spam</Button></div></div>)}</div></section>
  <div id="briefing-library" className="mt-8 scroll-mt-6"><h2 className="mb-3 text-2xl font-bold">Saved Briefings</h2><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search title, slug, or excerpt" className="max-w-xl border-[#607895] bg-[#0b1624] text-white" /></div><section className="mt-5 overflow-hidden rounded-xl border border-[#526d94]/40 bg-[#0c1624]">{isLoading ? <div className="p-8">Loading…</div> : filtered.length === 0 ? <div className="p-12 text-center text-[#aebdce]">No briefings yet. Create the first draft when you are ready.</div> : filtered.map((item) => <div key={item.id} className="grid gap-4 border-b border-[#526d94]/30 p-5 last:border-0 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="flex flex-wrap items-center gap-2"><span className="text-xl font-bold">{item.title}</span><Badge className="bg-[#193763] text-white">{item.status}</Badge><Badge variant="outline" className="border-[#617b9e] text-[#c9d7e7]">{item.contentType === "video" ? <Video className="mr-1 h-3 w-3" /> : <FileText className="mr-1 h-3 w-3" />}{item.contentType}</Badge>{item.isFeatured && <Badge className="bg-[#8b6b17] text-white">Featured</Badge>}</div><div className="mt-2 text-sm text-[#a4b4c6]">{item.category} · /{item.slug} · Updated {item.updatedAt ? new Date(item.updatedAt).toLocaleDateString() : "—"}</div></div><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={() => { setEditingId(item.id); setForm(toInput(item)); window.scrollTo({ top: 0, behavior: "smooth" }); }}><Pencil className="mr-1 h-4 w-4" />Edit</Button><Button asChild variant="outline" size="sm"><a href={`/aviation-briefings/preview/${item.id}`} target="_blank" rel="noreferrer"><Eye className="mr-1 h-4 w-4" />Preview</a></Button>{item.status === "published" ? <Button variant="outline" size="sm" onClick={() => action.mutate({ id: item.id, action: "unpublish" })}>Unpublish</Button> : <Button size="sm" className="bg-[#347edc] text-white" onClick={() => action.mutate({ id: item.id, action: "publish" })}>Publish</Button>}<Button variant="destructive" size="sm" onClick={() => { if (window.confirm(`Permanently delete “${item.title}”?`)) remove.mutate(item.id); }}><Trash2 className="h-4 w-4" /></Button></div></div>)}</section></>}
  </div></main>;
}
