import { useMemo, useState } from "react";
import { Link } from "wouter";
import { useMutation, useQuery } from "@tanstack/react-query";
import { ArrowLeft, Eye, FileText, Pencil, Plus, Trash2, Video } from "lucide-react";
import { BriefingEditor } from "@/components/aviation-briefings/BriefingEditor";
import type { AviationBriefing } from "@/components/aviation-briefings/types";
import type { AviationBriefingInput } from "@shared/config/aviationBriefings";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { useAuth } from "@/hooks/useAuth";
import { useToast } from "@/hooks/use-toast";
import { apiRequest, queryClient } from "@/lib/queryClient";

const emptyBriefing: AviationBriefingInput = { title: "", slug: "", excerpt: "", contentType: "article", category: "Flight Planning", status: "draft", isFeatured: false, featuredImageUrl: "", featuredImageStorageKey: "", featuredImageAlt: "", articleContent: [{ type: "paragraph", text: "" }], videoSourceType: null, videoUrl: "", videoStorageKey: "", videoThumbnailUrl: "", videoDurationSeconds: null, videoTranscript: "", supportingContent: [], contributors: [], relevantToolIds: [], seoTitle: "", seoDescription: "", publishedAt: null, scheduledAt: null };

function toInput(item: AviationBriefing): AviationBriefingInput { return { ...emptyBriefing, title: item.title, slug: item.slug, excerpt: item.excerpt, contentType: item.contentType, category: item.category, status: item.status as AviationBriefingInput["status"], isFeatured: item.isFeatured, featuredImageUrl: item.featuredImageUrl || "", featuredImageStorageKey: item.featuredImageStorageKey || "", featuredImageAlt: item.featuredImageAlt || "", articleContent: item.articleContent || [], videoSourceType: item.videoSourceType || null, videoUrl: item.videoUrl || "", videoThumbnailUrl: item.videoThumbnailUrl || "", videoDurationSeconds: item.videoDurationSeconds || null, videoTranscript: item.videoTranscript || "", supportingContent: item.supportingContent || [], contributors: item.contributors || [], relevantToolIds: item.relevantToolIds || [], seoTitle: item.seoTitle || "", seoDescription: item.seoDescription || "", publishedAt: item.publishedAt || null, scheduledAt: item.scheduledAt || null }; }

export default function AdminAviationBriefingsPage() {
  const { user, isLoading: authLoading } = useAuth();
  const { toast } = useToast();
  const [search, setSearch] = useState("");
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form, setForm] = useState<AviationBriefingInput>(emptyBriefing);
  const { data, isLoading } = useQuery<{ briefings: AviationBriefing[]; total: number; summaryRows: Array<{ status: string; contentType: string; featured: boolean; count: number }> }>({ queryKey: ["/api/admin/aviation-briefings"], queryFn: async () => { const response = await fetch("/api/admin/aviation-briefings", { credentials: "include" }); if (!response.ok) throw new Error("Super Admin access required"); return response.json(); }, enabled: Boolean(user?.isSuperAdmin) });
  const save = useMutation({ mutationFn: async () => { const isExisting = Boolean(editingId && editingId !== "new"); const response = await apiRequest(isExisting ? "PATCH" : "POST", isExisting ? `/api/admin/aviation-briefings/${editingId}` : "/api/admin/aviation-briefings", form); return response.json(); }, onSuccess: () => { toast({ title: "Briefing saved" }); setEditingId(null); setForm(emptyBriefing); queryClient.invalidateQueries({ queryKey: ["/api/admin/aviation-briefings"] }); }, onError: (error: Error) => toast({ title: "Unable to save briefing", description: error.message, variant: "destructive" }) });
  const action = useMutation({ mutationFn: ({ id, action }: { id: string; action: string }) => apiRequest("POST", `/api/admin/aviation-briefings/${id}/${action}`), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["/api/admin/aviation-briefings"] }) });
  const remove = useMutation({ mutationFn: (id: string) => apiRequest("DELETE", `/api/admin/aviation-briefings/${id}`), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["/api/admin/aviation-briefings"] }) });
  const filtered = (data?.briefings || []).filter((item) => `${item.title} ${item.slug} ${item.excerpt}`.toLowerCase().includes(search.toLowerCase()));
  const totals = useMemo(() => { const rows = data?.summaryRows || []; return { total: rows.reduce((sum, row) => sum + row.count, 0), published: rows.filter((r) => r.status === "published").reduce((s, r) => s + r.count, 0), drafts: rows.filter((r) => r.status === "draft").reduce((s, r) => s + r.count, 0), review: rows.filter((r) => r.status === "review").reduce((s, r) => s + r.count, 0), videos: rows.filter((r) => r.contentType === "video").reduce((s, r) => s + r.count, 0) }; }, [data]);
  if (authLoading) return <div className="min-h-screen bg-[#07101c] p-10 text-white">Loading…</div>;
  if (!user?.isSuperAdmin) return <div className="min-h-screen bg-[#07101c] p-10 text-white">Super Admin access is required.</div>;
  return <main className="min-h-screen bg-[#07101c] px-5 py-10 text-[#edf5ff] sm:px-8"><div className="mx-auto max-w-7xl"><Link href="/admin" className="inline-flex items-center text-sm text-[#8dbbfa]"><ArrowLeft className="mr-2 h-4 w-4" />Admin Dashboard</Link><div className="mt-5 flex flex-wrap items-end justify-between gap-4"><div><div className="text-sm font-bold uppercase tracking-[.2em] text-[#87b8f7]">Publishing</div><h1 className="mt-2 text-4xl font-black">Aviation Briefings</h1><p className="mt-2 text-[#aebdce]">Prepare, review, schedule, and publish RSF aviation content.</p></div><Button onClick={() => { setEditingId("new"); setForm({ ...emptyBriefing }); }} className="bg-[#347edc] text-white"><Plus className="mr-2 h-4 w-4" />New briefing</Button></div>
  {editingId ? <section className="mt-8 rounded-2xl border border-[#526d94]/40 bg-[#0c1624] p-5 sm:p-8"><div className="mb-7 flex justify-between"><h2 className="text-2xl font-bold">{editingId === "new" ? "Create briefing" : "Edit briefing"}</h2><Button variant="outline" onClick={() => setEditingId(null)}>Cancel</Button></div><BriefingEditor value={form} onChange={setForm} onSave={() => save.mutate()} saving={save.isPending} /></section> : <><section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{Object.entries(totals).map(([label, value]) => <div key={label} className="rounded-xl border border-[#526d94]/40 bg-[#0d1827] p-5"><div className="text-sm capitalize text-[#9fb0c4]">{label}</div><div className="mt-2 text-3xl font-bold">{value}</div></div>)}</section><div className="mt-8"><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search title, slug, or excerpt" className="max-w-xl border-[#607895] bg-[#0b1624] text-white" /></div><section className="mt-5 overflow-hidden rounded-xl border border-[#526d94]/40 bg-[#0c1624]">{isLoading ? <div className="p-8">Loading…</div> : filtered.length === 0 ? <div className="p-12 text-center text-[#aebdce]">No briefings yet. Create the first draft when you are ready.</div> : filtered.map((item) => <div key={item.id} className="grid gap-4 border-b border-[#526d94]/30 p-5 last:border-0 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="flex flex-wrap items-center gap-2"><span className="text-xl font-bold">{item.title}</span><Badge className="bg-[#193763] text-white">{item.status}</Badge><Badge variant="outline" className="border-[#617b9e] text-[#c9d7e7]">{item.contentType === "video" ? <Video className="mr-1 h-3 w-3" /> : <FileText className="mr-1 h-3 w-3" />}{item.contentType}</Badge>{item.isFeatured && <Badge className="bg-[#8b6b17] text-white">Featured</Badge>}</div><div className="mt-2 text-sm text-[#a4b4c6]">{item.category} · /{item.slug} · Updated {item.updatedAt ? new Date(item.updatedAt).toLocaleDateString() : "—"}</div></div><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={() => { setEditingId(item.id); setForm(toInput(item)); }}><Pencil className="mr-1 h-4 w-4" />Edit</Button><Button asChild variant="outline" size="sm"><a href={`/aviation-briefings/preview/${item.id}`} target="_blank" rel="noreferrer"><Eye className="mr-1 h-4 w-4" />Preview</a></Button>{item.status === "published" ? <Button variant="outline" size="sm" onClick={() => action.mutate({ id: item.id, action: "unpublish" })}>Unpublish</Button> : <Button size="sm" className="bg-[#347edc] text-white" onClick={() => action.mutate({ id: item.id, action: "publish" })}>Publish</Button>}<Button variant="destructive" size="sm" onClick={() => { if (window.confirm(`Permanently delete “${item.title}”?`)) remove.mutate(item.id); }}><Trash2 className="h-4 w-4" /></Button></div></div>)}</section></>}
  </div></main>;
}
