import { useEffect, useState } from "react";
import { useParams } from "wouter";
import { useMutation, useQuery } from "@tanstack/react-query";
import { CheckCircle2, ShieldCheck } from "lucide-react";
import { Input } from "@/components/ui/input"; import { Textarea } from "@/components/ui/textarea"; import { Label } from "@/components/ui/label"; import { Button } from "@/components/ui/button"; import { Checkbox } from "@/components/ui/checkbox";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { AVIATION_BRIEFING_CATEGORIES, type ContributorSubmissionInput } from "@shared/config/aviationBriefings";
import { RSF_TOOLS } from "@/lib/tool-registry"; import { apiRequest, queryClient } from "@/lib/queryClient"; import { useToast } from "@/hooks/use-toast"; import { trackEvent } from "@/lib/analytics";

const empty: ContributorSubmissionInput = { contributorName:"",contributorEmail:"",contributorTitle:"",contributorCredentials:"",contributorOrganization:"",contributorBio:"",contributorProfileImageUrl:"",contributorWebsiteUrl:"",contributorYoutubeUrl:"",contributorVimeoUrl:"",contributorLinkedinUrl:"",contributorOtherUrl:"",title:"",description:"",category:"Flight Planning",videoProvider:"youtube",videoUrl:"",originalPublicationUrl:"",thumbnailUrl:"",videoDurationSeconds:null,transcript:"",contentOutline:"",intendedAudience:"",relevantToolIds:[],additionalNotes:"",isSponsored:false,sponsorName:"",hasAffiliateRelationship:false,affiliateDisclosure:"",promotesProductsOrServices:false,receivedCompensation:false,commercialRelationshipNotes:"",agreementAccepted:false };
const field="border-[#607895] bg-[#0b1624] text-white placeholder:text-[#7f92aa]";
export default function AviationBriefingSubmitPage(){
 const {token}=useParams<{token:string}>(); const {toast}=useToast(); const [form,setForm]=useState(empty); const update=(key:keyof ContributorSubmissionInput,value:any)=>setForm(current=>({...current,[key]:value}));
 const {data,isLoading,error}=useQuery<any>({queryKey:["contributor-invite",token],queryFn:async()=>{const r=await fetch(`/api/aviation-briefing-submissions/access/${encodeURIComponent(token)}`);if(!r.ok)throw new Error("This invitation is invalid, expired, or revoked.");return r.json();},retry:false});
 useEffect(()=>{if(!data)return;const s=data.submission;setForm(current=>({...current,contributorName:s?.contributorName||data.invitation.contributorName,contributorEmail:data.invitation.contributorEmail,contributorOrganization:s?.contributorOrganization||data.invitation.organization||"",...(s?{contributorTitle:s.contributorTitle||"",contributorCredentials:s.contributorCredentials||"",contributorBio:s.contributorBio||"",contributorProfileImageUrl:s.contributorProfileImageUrl||"",contributorWebsiteUrl:s.contributorLinksJson?.website||"",contributorYoutubeUrl:s.contributorLinksJson?.youtube||"",contributorVimeoUrl:s.contributorLinksJson?.vimeo||"",contributorLinkedinUrl:s.contributorLinksJson?.linkedin||"",title:s.title,description:s.description,category:s.category,videoProvider:s.videoProvider,videoUrl:s.videoUrl,originalPublicationUrl:s.originalPublicationUrl||"",thumbnailUrl:s.thumbnailUrl||"",videoDurationSeconds:s.videoDurationSeconds,transcript:s.transcript||"",contentOutline:s.contentOutline||"",intendedAudience:s.intendedAudience||"",relevantToolIds:s.relevantToolIdsJson||[],additionalNotes:s.additionalNotes||"",...s.disclosuresJson}: {})}));trackEvent("aviation_contributor_invitation_opened");},[data?.invitation?.contributorEmail]);
 const save=useMutation({mutationFn:(submit:boolean)=>apiRequest("POST",`/api/aviation-briefing-submissions/access/${token}/${submit?"submit":"draft"}`,form),onSuccess:(_,submitted)=>{toast({title:submitted?"Submitted for editorial review":"Draft saved"});trackEvent(submitted?"aviation_briefing_submission_submitted":"aviation_briefing_submission_draft_saved");queryClient.invalidateQueries({queryKey:["contributor-invite",token]});},onError:(e:Error)=>toast({title:"Unable to save",description:e.message,variant:"destructive"})});
 if(isLoading)return <div className="min-h-screen bg-[#07101c] p-12 text-center text-white">Opening secure invitation…</div>; if(error)return <div className="min-h-screen bg-[#07101c] p-12 text-center text-white">{(error as Error).message}</div>; const status=data?.submission?.status||"draft"; const editable=["draft","revision_requested"].includes(status);
 return <main className="min-h-screen bg-[#07101c] px-5 py-12 text-white"><div className="mx-auto max-w-4xl"><div className="text-sm font-bold uppercase tracking-[.2em] text-[#8ebeff]">Ready Set Fly | Briefings · Curated Contributor Program</div><h1 className="mt-3 text-4xl font-black">Submit a Briefing</h1><p className="mt-4 leading-7 text-[#b8c7d9]">Submission does not guarantee publication. RSF reviews every contribution and may request revisions or edit presentation. You retain ownership while granting RSF non-exclusive permission to display, promote, excerpt, link to, or remove the submitted content.</p><div className="mt-6 rounded-xl border border-[#54729a] bg-[#0d1928] p-4"><b>Status:</b> {status.replaceAll("_"," ")}{data?.submission?.revisionRequest&&<p className="mt-2 text-amber-200"><b>Revision requested:</b> {data.submission.revisionRequest}</p>}</div>{!editable?<div className="mt-10 rounded-xl border border-emerald-700 bg-emerald-950/40 p-8 text-center"><CheckCircle2 className="mx-auto h-10 w-10"/><h2 className="mt-3 text-2xl font-bold">Your submission is with the RSF editorial team.</h2><p className="mt-2 text-emerald-100">Return to this secure link to view status or requested revisions.</p></div>:<div className="mt-10 space-y-9">
 <Section title="Contributor information"><Grid fields={[["Contributor name","contributorName"],["Email address","contributorEmail"],["Professional title","contributorTitle"],["Aviation credentials","contributorCredentials"],["Organization","contributorOrganization"],["Profile image URL","contributorProfileImageUrl"],["Website","contributorWebsiteUrl"],["YouTube channel","contributorYoutubeUrl"],["Vimeo profile","contributorVimeoUrl"],["LinkedIn profile","contributorLinkedinUrl"]]} form={form} update={update}/><Label>Short biography</Label><Textarea className={field} value={form.contributorBio} onChange={e=>update("contributorBio",e.target.value)}/></Section>
 <Section title="Video briefing"><Grid fields={[["Briefing title","title"],["Video URL","videoUrl"],["Original publication URL","originalPublicationUrl"],["Suggested thumbnail URL","thumbnailUrl"],["Duration in seconds","videoDurationSeconds"],["Intended audience","intendedAudience"]]} form={form} update={update}/><div className="grid gap-4 sm:grid-cols-2"><div><Label>Category</Label><Select value={form.category} onValueChange={v=>update("category",v)}><SelectTrigger className={field}><SelectValue/></SelectTrigger><SelectContent>{AVIATION_BRIEFING_CATEGORIES.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div><div><Label>Video provider</Label><Select value={form.videoProvider} onValueChange={v=>update("videoProvider",v)}><SelectTrigger className={field}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="youtube">YouTube</SelectItem><SelectItem value="vimeo">Vimeo</SelectItem></SelectContent></Select></div></div><Label>Short description</Label><Textarea className={field} value={form.description} onChange={e=>update("description",e.target.value)}/><Label>Transcript</Label><Textarea rows={8} className={field} value={form.transcript} onChange={e=>update("transcript",e.target.value)}/><Label>Detailed outline</Label><Textarea rows={5} className={field} value={form.contentOutline} onChange={e=>update("contentOutline",e.target.value)}/></Section>
 <Section title="Relevant Ready Set Fly tools"><div className="grid gap-2 sm:grid-cols-2">{RSF_TOOLS.map(t=><label key={t.id} className="flex gap-2 rounded border border-[#526b8d] p-3"><Checkbox checked={form.relevantToolIds.includes(t.id)} onCheckedChange={c=>update("relevantToolIds",c?[...form.relevantToolIds,t.id]:form.relevantToolIds.filter(x=>x!==t.id))}/><span>{t.title}</span></label>)}</div></Section>
 <Section title="Commercial disclosures"><Checks form={form} update={update}/><Grid fields={[["Sponsor name","sponsorName"],["Affiliate disclosure","affiliateDisclosure"],["Professional or financial relationship details","commercialRelationshipNotes"]]} form={form} update={update}/></Section>
 <Section title="Contributor agreement"><div className="space-y-2 text-sm leading-6 text-[#c7d4e3]">{["I own this content or have permission to submit it.","I grant Ready Set Fly non-exclusive permission to embed, display, promote, excerpt, and link to it.","I retain ownership of my original content.","Submission does not guarantee publication and RSF may edit presentation.","RSF may decline, unpublish, or remove the content.","I disclosed sponsorships, affiliate relationships, compensation, and commercial interests.","My credentials and professional information are accurate.","This educational content does not replace official information, instruction, or pilot-in-command decisions."].map(x=><p key={x}>• {x}</p>)}</div><label className="mt-5 flex gap-3 rounded-lg border border-[#6787ae] p-4"><Checkbox checked={form.agreementAccepted} onCheckedChange={c=>update("agreementAccepted",c===true)}/><span>I accept the contributor agreement above.</span></label></Section>
 <div className="flex justify-end gap-3"><Button variant="outline" onClick={()=>save.mutate(false)} disabled={save.isPending}>Save draft</Button><Button className="bg-[#347edc] text-white" onClick={()=>save.mutate(true)} disabled={save.isPending||!form.agreementAccepted}><ShieldCheck className="mr-2 h-4 w-4"/>Submit for review</Button></div></div>}</div></main>;
}
function Section({title,children}:{title:string;children:any}){return <section className="space-y-4 rounded-2xl border border-[#526d94]/40 bg-[#0c1624] p-5 sm:p-7"><h2 className="text-2xl font-bold">{title}</h2>{children}</section>}
function Grid({fields,form,update}:{fields:string[][];form:any;update:any}){return <div className="grid gap-4 sm:grid-cols-2">{fields.map(([label,key])=><div key={key}><Label>{label}</Label><Input className={field} value={form[key]??""} type={key==="contributorEmail"?"email":key==="videoDurationSeconds"?"number":"text"} disabled={key==="contributorEmail"} onChange={e=>update(key,key==="videoDurationSeconds"?(e.target.value?Number(e.target.value):null):e.target.value)}/></div>)}</div>}
function Checks({form,update}:{form:any;update:any}){return <div className="grid gap-3 sm:grid-cols-2">{[["Sponsored content","isSponsored"],["Affiliate links or relationships","hasAffiliateRelationship"],["Promotes products or services","promotesProductsOrServices"],["Compensation received","receivedCompensation"]].map(([label,key])=><label key={key} className="flex gap-2"><Checkbox checked={form[key]} onCheckedChange={c=>update(key,c===true)}/>{label}</label>)}</div>}
