import { useQuery } from "@tanstack/react-query";
import { useParams } from "wouter";
import { Download, ExternalLink } from "lucide-react";
import { apiUrl } from "@/lib/api";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

export default function CourtyardSalesTransitionShare() {
  const { token = "" } = useParams<{ token: string }>();
  const query = useQuery({ queryKey: ["sales-transition-share", token], queryFn: async () => { const response = await fetch(apiUrl(`/api/courtyard/sales-intelligence/transition-share/${token}`)); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Transition could not be opened."); return body; }, enabled: !!token, retry: false });
  if (query.isLoading) return <div className="min-h-screen bg-[#f7f1e7] p-8 text-[#201814]">Loading transition package…</div>;
  if (query.error) return <div className="flex min-h-screen items-center justify-center bg-[#f7f1e7] p-6"><Card className="max-w-lg bg-white"><CardHeader><CardTitle>Link unavailable</CardTitle></CardHeader><CardContent>{(query.error as Error).message}</CardContent></Card></div>;
  const { transition, items, documents, allowDownloads } = query.data;
  const categories = Array.from(new Set(items.map((item: any) => item.category))) as string[];
  return <div className="min-h-screen bg-[#f7f1e7] text-[#201814]"><header className="border-b border-[#deceba] bg-[#fffaf2] px-4 py-5"><div className="mx-auto max-w-5xl"><div className="text-xs font-bold uppercase tracking-[.2em] text-[#8a6b3f]">Courtyard Austin Lakeline</div><h1 className="text-3xl font-semibold">{transition.title}</h1><p className="text-[#5f5247]">Secure sales transition package · {transition.departingUserName || "Sales handoff"}</p></div></header><main className="mx-auto max-w-5xl space-y-5 px-4 py-6">{transition.summary&&<Card className="border-[#cdbda8] bg-white"><CardContent className="p-5">{transition.summary}</CardContent></Card>}{categories.map(category=><Card key={category} className="border-[#cdbda8] bg-[#fffaf2]"><CardHeader><CardTitle className="capitalize">{category}</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2">{items.filter((x:any)=>x.category===category).map((x:any)=><div key={x.id} className="rounded-lg border border-[#deceba] bg-white p-4"><div className="flex justify-between gap-2"><b>{x.title}</b><Badge variant="outline">{String(x.status).replaceAll("_"," ")}</Badge></div><p className="mt-1 text-sm text-[#5f5247]">{x.description}</p>{x.url&&<a className="mt-2 inline-flex items-center text-sm text-blue-700 underline" href={x.url} target="_blank" rel="noreferrer"><ExternalLink className="mr-1 h-3 w-3"/>Open resource</a>}<div className="mt-2 text-xs text-[#6e5d50]">{x.ownerName?`Owner: ${x.ownerName}`:""}{x.dueDate?` · Due ${x.dueDate}`:""}</div></div>)}</CardContent></Card>)}<Card className="border-[#cdbda8] bg-[#fffaf2]"><CardHeader><CardTitle>Document index</CardTitle></CardHeader><CardContent className="space-y-2">{documents.map((x:any)=><div key={x.id} className="flex items-center justify-between rounded border bg-white p-3"><span>{x.filename} · {x.category}</span>{allowDownloads&&<Button asChild size="sm" variant="outline"><a href={apiUrl(`/api/courtyard/sales-intelligence/transition-share/${token}/documents/${x.id}`)}><Download className="mr-1 h-4 w-4"/>Download</a></Button>}</div>)}{!documents.length&&<p className="text-sm text-[#5f5247]">No shared documents.</p>}</CardContent></Card></main></div>;
}
