import crypto from "crypto";
import type { Express } from "express";
import { and, desc, eq } from "drizzle-orm";
import { z } from "zod";
import { aviationBriefings, aviationBriefingSubmissions, aviationContributorInvitations } from "@shared/schema";
import { AVIATION_SUBMISSION_AGREEMENT_VERSION, contributorSubmissionSchema } from "@shared/config/aviationBriefings";
import { db } from "../db";
import { isAuthenticated, isSuperAdmin } from "../auth";
import { createSoftAuthRateLimiter } from "../middleware/rateLimit";

const accessLimit = createSoftAuthRateLimiter({ windowMs: 15 * 60_000, anonMax: 40, authMax: 100, key: "aviation_contributor_access" });
const tokenHash = (token: string) => crypto.createHash("sha256").update(token).digest("hex");
const newToken = () => crypto.randomBytes(32).toString("base64url");
const userId = (req: any) => String(req.user?.id || req.user?.claims?.sub || req.session?.userId || "") || null;

async function invitationForToken(token: string, markOpened = false) {
  if (!/^[A-Za-z0-9_-]{40,100}$/.test(token)) return null;
  const [invite] = await db.select().from(aviationContributorInvitations).where(eq(aviationContributorInvitations.tokenHash, tokenHash(token))).limit(1);
  if (!invite || invite.status !== "active" || invite.revokedAt || (invite.expiresAt && invite.expiresAt <= new Date())) return null;
  if (markOpened && !invite.openedAt) await db.update(aviationContributorInvitations).set({ openedAt: new Date(), updatedAt: new Date() }).where(eq(aviationContributorInvitations.id, invite.id));
  return invite;
}

function contributorSafe(row: typeof aviationBriefingSubmissions.$inferSelect | null) {
  if (!row) return null;
  const { internalReviewNotes: _internal, reviewChecklistJson: _checklist, assignedReviewerUserId: _reviewer, ...safe } = row;
  return { ...safe, revisionRequest: row.revisionRequest || null };
}

function submissionValues(input: z.infer<typeof contributorSubmissionSchema>, invite: typeof aviationContributorInvitations.$inferSelect) {
  return { contributorName: input.contributorName, contributorEmail: invite.contributorEmail, contributorTitle: input.contributorTitle || null, contributorCredentials: input.contributorCredentials || null, contributorOrganization: input.contributorOrganization || null, contributorBio: input.contributorBio || null, contributorProfileImageUrl: input.contributorProfileImageUrl || null, contributorLinksJson: { website: input.contributorWebsiteUrl, youtube: input.contributorYoutubeUrl, vimeo: input.contributorVimeoUrl, linkedin: input.contributorLinkedinUrl, other: input.contributorOtherUrl }, title: input.title, description: input.description, category: input.category, videoProvider: input.videoProvider, videoUrl: input.videoUrl, originalPublicationUrl: input.originalPublicationUrl || null, thumbnailUrl: input.thumbnailUrl || null, videoDurationSeconds: input.videoDurationSeconds, transcript: input.transcript || null, contentOutline: input.contentOutline || null, intendedAudience: input.intendedAudience || null, relevantToolIdsJson: input.relevantToolIds, additionalNotes: input.additionalNotes || null, disclosuresJson: { isSponsored: input.isSponsored, sponsorName: input.sponsorName, hasAffiliateRelationship: input.hasAffiliateRelationship, affiliateDisclosure: input.affiliateDisclosure, promotesProductsOrServices: input.promotesProductsOrServices, receivedCompensation: input.receivedCompensation, commercialRelationshipNotes: input.commercialRelationshipNotes }, updatedAt: new Date() };
}

export function registerAviationBriefingSubmissionRoutes(app: Express) {
  app.get("/api/aviation-briefing-submissions/access/:token", accessLimit, async (req, res, next) => { try { const invite = await invitationForToken(req.params.token, true); if (!invite) return res.status(404).json({ error: "This invitation is invalid, expired, or revoked." }); const [submission] = await db.select().from(aviationBriefingSubmissions).where(eq(aviationBriefingSubmissions.invitationId, invite.id)).limit(1); res.json({ invitation: { contributorName: invite.contributorName, contributorEmail: invite.contributorEmail, organization: invite.organization, expiresAt: invite.expiresAt }, submission: contributorSafe(submission || null), agreementVersion: AVIATION_SUBMISSION_AGREEMENT_VERSION }); } catch (e) { next(e); } });

  app.post("/api/aviation-briefing-submissions/access/:token/draft", accessLimit, async (req, res, next) => { try { const invite = await invitationForToken(req.params.token); if (!invite) return res.status(404).json({ error: "This invitation is invalid, expired, or revoked." }); const parsed = contributorSubmissionSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ error: "Please correct the submission fields.", validation: parsed.error.format() }); const [existing] = await db.select().from(aviationBriefingSubmissions).where(eq(aviationBriefingSubmissions.invitationId, invite.id)).limit(1); if (existing && !["draft", "revision_requested"].includes(existing.status)) return res.status(423).json({ error: "This submission cannot currently be edited." }); const values = submissionValues(parsed.data, invite); const [row] = existing ? await db.update(aviationBriefingSubmissions).set(values).where(eq(aviationBriefingSubmissions.id, existing.id)).returning() : await db.insert(aviationBriefingSubmissions).values({ invitationId: invite.id, ...values, status: "draft" }).returning(); if (!invite.firstSubmissionAt) await db.update(aviationContributorInvitations).set({ firstSubmissionAt: new Date(), updatedAt: new Date() }).where(eq(aviationContributorInvitations.id, invite.id)); res.json({ submission: contributorSafe(row) }); } catch (e) { next(e); } });

  app.post("/api/aviation-briefing-submissions/access/:token/submit", accessLimit, async (req, res, next) => { try { const invite = await invitationForToken(req.params.token); if (!invite) return res.status(404).json({ error: "This invitation is invalid, expired, or revoked." }); const parsed = contributorSubmissionSchema.safeParse(req.body); if (!parsed.success || !parsed.data.agreementAccepted) return res.status(400).json({ error: "Complete the required fields and accept the contributor agreement." }); const [existing] = await db.select().from(aviationBriefingSubmissions).where(eq(aviationBriefingSubmissions.invitationId, invite.id)).limit(1); if (existing && !["draft", "revision_requested"].includes(existing.status)) return res.status(423).json({ error: "This submission cannot currently be submitted." }); const now = new Date(); const values = { ...submissionValues(parsed.data, invite), status: "submitted", agreementAccepted: true, agreementVersion: AVIATION_SUBMISSION_AGREEMENT_VERSION, agreementAcceptedAt: now, submittedAt: now, revisionRequest: null }; const [row] = existing ? await db.update(aviationBriefingSubmissions).set(values).where(eq(aviationBriefingSubmissions.id, existing.id)).returning() : await db.insert(aviationBriefingSubmissions).values({ invitationId: invite.id, ...values }).returning(); res.json({ submission: contributorSafe(row) }); } catch (e) { next(e); } });

  app.post("/api/aviation-briefing-submissions/access/:token/withdraw", accessLimit, async (req, res, next) => { try { const invite = await invitationForToken(req.params.token); if (!invite) return res.status(404).json({ error: "Invalid invitation." }); const [row] = await db.update(aviationBriefingSubmissions).set({ status: "withdrawn", withdrawnAt: new Date(), updatedAt: new Date() }).where(and(eq(aviationBriefingSubmissions.invitationId, invite.id), eq(aviationBriefingSubmissions.status, "submitted"))).returning(); if (!row) return res.status(409).json({ error: "Only a submitted item can be withdrawn." }); res.json({ submission: contributorSafe(row) }); } catch (e) { next(e); } });

  app.get("/api/admin/aviation-briefing-invitations", isAuthenticated, isSuperAdmin, async (_req, res, next) => { try { res.json({ invitations: await db.select().from(aviationContributorInvitations).orderBy(desc(aviationContributorInvitations.createdAt)) }); } catch (e) { next(e); } });
  app.post("/api/admin/aviation-briefing-invitations", isAuthenticated, isSuperAdmin, async (req: any, res, next) => { try { const parsed = z.object({ contributorName: z.string().min(2).max(200), contributorEmail: z.string().email(), organization: z.string().max(300).optional(), internalNote: z.string().max(3000).optional(), expiresAt: z.string().datetime().nullable().optional() }).safeParse(req.body); if (!parsed.success) return res.status(400).json({ error: "Invalid invitation." }); const token = newToken(); const [invite] = await db.insert(aviationContributorInvitations).values({ ...parsed.data, expiresAt: parsed.data.expiresAt ? new Date(parsed.data.expiresAt) : null, tokenHash: tokenHash(token), createdByUserId: userId(req) }).returning(); res.status(201).json({ invitation: invite, submissionUrl: `${req.protocol}://${req.get("host")}/briefings/submit/${token}` }); } catch (e) { next(e); } });
  app.post("/api/admin/aviation-briefing-invitations/:id/revoke", isAuthenticated, isSuperAdmin, async (req, res, next) => { try { const [row] = await db.update(aviationContributorInvitations).set({ status: "revoked", revokedAt: new Date(), updatedAt: new Date() }).where(eq(aviationContributorInvitations.id, req.params.id)).returning(); if (!row) return res.status(404).json({ error: "Invitation not found" }); res.json({ invitation: row }); } catch (e) { next(e); } });
  app.post("/api/admin/aviation-briefing-invitations/:id/regenerate", isAuthenticated, isSuperAdmin, async (req, res, next) => { try { const token = newToken(); const [row] = await db.update(aviationContributorInvitations).set({ tokenHash: tokenHash(token), status: "active", revokedAt: null, updatedAt: new Date() }).where(eq(aviationContributorInvitations.id, req.params.id)).returning(); if (!row) return res.status(404).json({ error: "Invitation not found" }); res.json({ invitation: row, submissionUrl: `${req.protocol}://${req.get("host")}/briefings/submit/${token}` }); } catch (e) { next(e); } });

  app.get("/api/admin/aviation-briefing-submissions", isAuthenticated, isSuperAdmin, async (_req, res, next) => { try { res.json({ submissions: await db.select().from(aviationBriefingSubmissions).orderBy(desc(aviationBriefingSubmissions.updatedAt)) }); } catch (e) { next(e); } });
  app.patch("/api/admin/aviation-briefing-submissions/:id", isAuthenticated, isSuperAdmin, async (req, res, next) => { try { const parsed = z.object({ internalReviewNotes: z.string().max(20000).optional(), revisionRequest: z.string().max(10000).optional(), credentialsReviewed: z.boolean().optional(), aviationReviewRecommended: z.boolean().optional(), aviationReviewCompleted: z.boolean().optional(), reviewChecklistJson: z.record(z.boolean()).optional() }).safeParse(req.body); if (!parsed.success) return res.status(400).json({ error: "Invalid review update" }); const [row] = await db.update(aviationBriefingSubmissions).set({ ...parsed.data, updatedAt: new Date() }).where(eq(aviationBriefingSubmissions.id, req.params.id)).returning(); res.json({ submission: row }); } catch (e) { next(e); } });
  app.post("/api/admin/aviation-briefing-submissions/:id/:action", isAuthenticated, isSuperAdmin, async (req, res, next) => { try { const action = z.enum(["under-review", "request-revision", "approve", "reject", "archive"]).safeParse(req.params.action); if (!action.success) return res.status(404).json({ error: "Unknown action" }); const map = { "under-review": "under_review", "request-revision": "revision_requested", approve: "approved", reject: "rejected", archive: "archived" } as const; const status = map[action.data]; const now = new Date(); const [row] = await db.update(aviationBriefingSubmissions).set({ status, revisionRequest: action.data === "request-revision" ? String(req.body?.message || "Please review the requested revisions.").slice(0,10000) : undefined, reviewedAt: now, approvedAt: status === "approved" ? now : undefined, rejectedAt: status === "rejected" ? now : undefined, updatedAt: now }).where(eq(aviationBriefingSubmissions.id, req.params.id)).returning(); if (!row) return res.status(404).json({ error: "Submission not found" }); res.json({ submission: row }); } catch (e) { next(e); } });
  app.post("/api/admin/aviation-briefing-submissions/:id/convert-to-briefing", isAuthenticated, isSuperAdmin, async (req: any, res, next) => { try { const [submission] = await db.select().from(aviationBriefingSubmissions).where(eq(aviationBriefingSubmissions.id, req.params.id)).limit(1); if (!submission || submission.status !== "approved") return res.status(409).json({ error: "Approve the submission before conversion." }); if (submission.publishedBriefingId) return res.status(409).json({ error: "This submission has already been converted." }); const links = submission.contributorLinksJson || {}; const contributor = { name: submission.contributorName, role: "Presenter", professionalTitle: submission.contributorTitle || "", aviationCredentials: submission.contributorCredentials || "", bio: submission.contributorBio || "", profileImageUrl: submission.contributorProfileImageUrl || "", organization: submission.contributorOrganization || "", profileUrl: links.website || links.youtube || "", websiteUrl: links.website || "", youtubeUrl: links.youtube || "", vimeoUrl: links.vimeo || "", linkedinUrl: links.linkedin || "", credentialVerificationNote: submission.credentialsReviewed ? "Contributor credentials reviewed by Ready Set Fly." : "Credentials provided by the contributor." }; const slugBase = submission.title.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,160); const [briefing] = await db.insert(aviationBriefings).values({ title: submission.title, slug: `${slugBase}-${submission.id.slice(0,6)}`, excerpt: submission.description, contentType: "video", category: submission.category, status: "draft", videoSourceType: submission.videoProvider, videoUrl: submission.videoUrl, videoThumbnailUrl: submission.thumbnailUrl, videoDurationSeconds: submission.videoDurationSeconds, videoTranscript: submission.transcript, supportingContentJson: submission.contentOutline ? [{ type: "paragraph", text: submission.contentOutline }] : [], contributorsJson: [contributor], relevantToolIdsJson: submission.relevantToolIdsJson, featuredImageUrl: submission.thumbnailUrl, createdByUserId: userId(req), updatedByUserId: userId(req) }).returning(); await db.update(aviationBriefingSubmissions).set({ publishedBriefingId: briefing.id, updatedAt: new Date() }).where(eq(aviationBriefingSubmissions.id, submission.id)); res.status(201).json({ briefing }); } catch (e) { next(e); } });
}
