// @ts-nocheck -- This server module uses runtime-supported Map iterator spreading.
import type { Express } from "express";
import express from "express";
import multer from "multer";
import crypto from "crypto";
import { and, asc, desc, eq, inArray } from "drizzle-orm";
import { db } from "../db";
import { courtyardHotelUserAccess, courtyardHotels, courtyardSalesImportBatches, courtyardSalesProduction, courtyardSalesRawRows, tipsUsers } from "@shared/schema";
import { MAX_SALES_IMPORT_BYTES, parseSalesImport, recoveryPriority } from "../courtyardSalesImport";

const DEFAULT_HOTEL_ID = "courtyard-austin-lakeline";
const RECOVERY_MONTHS = 3;
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: MAX_SALES_IMPORT_BYTES, files: 1 } });
const accessMap = (user:any) => user?.toolAccessJson && typeof user.toolAccessJson === "object" ? user.toolAccessJson : {};
const allowed = (user:any) => { const a=accessMap(user); return a.salesintelligence ?? a.dosreporting ?? (user?.role === "super_admin" || user?.role === "manager"); };
const admin = (user:any) => user?.role === "super_admin" || user?.role === "manager";
async function auth(req:any,res:any,next:any){try{const id=req.session?.tipsUserId;if(!id)return res.status(401).json({error:"Courtyard login is required."});const [user]=await db.select().from(tipsUsers).where(eq(tipsUsers.id,String(id))).limit(1);if(!user||user.disabledAt||user.mustChangePassword)return res.status(401).json({error:"Courtyard login is required."});if(!allowed(user))return res.status(403).json({error:"Sales Intelligence access is not enabled for this account."});let hotels=await db.select({hotel:courtyardHotels}).from(courtyardHotelUserAccess).innerJoin(courtyardHotels,eq(courtyardHotelUserAccess.hotelId,courtyardHotels.id)).where(eq(courtyardHotelUserAccess.userId,user.id));if(!hotels.length&&admin(user)){const fallback=await db.select().from(courtyardHotels).where(eq(courtyardHotels.id,DEFAULT_HOTEL_ID));hotels=fallback.map(h=>({hotel:h}));}req.salesUser=user;req.salesHotels=hotels.map(h=>h.hotel);next();}catch(e){next(e)}}
function hasHotel(req:any,id:string){return req.salesHotels.some((h:any)=>h.id===id)}
const n=(v:any)=>Number(v||0); const periodIndex=(y:number,m:number)=>y*12+m-1; const periodLabel=(y:number,m:number)=>new Date(y,m-1,1).toLocaleDateString("en-US",{month:"short",year:"numeric",timeZone:"UTC"});
function summarize(rows:any[]){const map=new Map<string,any>();for(const r of rows){let a=map.get(r.normalizedAccountKey);if(!a){a={key:r.normalizedAccountKey,displayName:r.globalUltimateAccountName||r.accountName||"Unnamed account",globalUltimateAccountName:r.globalUltimateAccountName,highestLevelAccountId:r.highestLevelAccountId,accountId:r.accountId,accountType:r.accountType,marketCategory:r.marketCategory,marketSegment:r.marketSegment,rateProgram:r.rateProgram,roomNights:0,roomRevenue:0,losNumerator:0,months:new Map(),bookingOffices:new Set()};map.set(r.normalizedAccountKey,a)}a.roomNights+=n(r.roomNights);a.roomRevenue+=n(r.roomRevenue);a.losNumerator+=n(r.averageLos)*n(r.roomNights);a.bookingOffices.add(r.bookingOffice);const pi=periodIndex(r.reportYear,r.reportMonth);let month=a.months.get(pi)||{year:r.reportYear,month:r.reportMonth,roomNights:0,roomRevenue:0,losNumerator:0,bookingOffices:new Set()};month.roomNights+=n(r.roomNights);month.roomRevenue+=n(r.roomRevenue);month.losNumerator+=n(r.averageLos)*n(r.roomNights);month.bookingOffices.add(r.bookingOffice);a.months.set(pi,month)}return [...map.values()].map(a=>{const history=[...a.months.entries()].sort((x,y)=>x[0]-y[0]);const first=history[0]?.[0],last=history.at(-1)?.[0];return {...a,months:undefined,bookingOffices:[...a.bookingOffices].filter(Boolean),adr:a.roomNights>0?a.roomRevenue/a.roomNights:0,averageLos:a.roomNights>0?a.losNumerator/a.roomNights:0,firstPeriod:first,lastPeriod:last,history:history.map(([index,m]:any)=>({...m,index,label:periodLabel(m.year,m.month),adr:m.roomNights>0?m.roomRevenue/m.roomNights:0,averageLos:m.roomNights>0?m.losNumerator/m.roomNights:0,bookingOffices:[...m.bookingOffices].filter(Boolean)}))}})}

export function registerCourtyardSalesIntelligenceRoutes(app:Express){const router=express.Router();router.use(auth);
 router.get("/me",(req:any,res)=>res.json({user:{id:req.salesUser.id,name:req.salesUser.employeeDisplayName||req.salesUser.email,isAdmin:admin(req.salesUser)},hotels:req.salesHotels,recoveryThresholdMonths:RECOVERY_MONTHS}));
 router.post("/preview",upload.single("file"),(req:any,res,next)=>{try{if(!req.file)return res.status(400).json({error:"Choose a report file."});const p=parseSalesImport(req.file.buffer);res.json({detectedDelimiter:p.delimiter,headers:p.rawHeaders,rowsFound:p.rowsFound,acceptedRows:p.accepted.length,rejectedRows:p.rejected.length,duplicateRows:p.duplicateRowCount,warnings:p.warnings,preview:p.accepted.slice(0,5).map(r=>({account:r.globalUltimateAccountName||r.accountName,bookingOffice:r.bookingOffice,roomNights:r.roomNights,roomRevenue:r.roomRevenue}))});}catch(e:any){res.status(400).json({error:e.message})}});
 router.post("/import",upload.single("file"),async(req:any,res,next)=>{try{if(!req.file)return res.status(400).json({error:"Choose a report file."});const hotelId=String(req.body.hotelId||"");const reportYear=Number(req.body.reportYear),reportMonth=Number(req.body.reportMonth),replace=String(req.body.replace)==="true";if(!hasHotel(req,hotelId))return res.status(403).json({error:"You do not have access to that property."});if(!Number.isInteger(reportYear)||reportYear<2000||reportYear>2100||!Number.isInteger(reportMonth)||reportMonth<1||reportMonth>12)return res.status(400).json({error:"Choose a valid report month and year."});const checksum=crypto.createHash("sha256").update(req.file.buffer).digest("hex");const exact=await db.select().from(courtyardSalesImportBatches).where(and(eq(courtyardSalesImportBatches.hotelId,hotelId),eq(courtyardSalesImportBatches.fileChecksum,checksum),eq(courtyardSalesImportBatches.status,"completed"))).limit(1);if(exact.length&&!replace)return res.status(409).json({error:"This exact file has already been imported.",code:"duplicate_file"});const existing=await db.select().from(courtyardSalesImportBatches).where(and(eq(courtyardSalesImportBatches.hotelId,hotelId),eq(courtyardSalesImportBatches.reportYear,reportYear),eq(courtyardSalesImportBatches.reportMonth,reportMonth),eq(courtyardSalesImportBatches.status,"completed")));if(existing.length&&!replace)return res.status(409).json({error:"This property already has data for that month. Confirm Replace Month to continue.",code:"duplicate_month"});if(existing.length&&replace){if(!admin(req.salesUser))return res.status(403).json({error:"Manager access is required to replace an import."});await db.update(courtyardSalesImportBatches).set({status:"replaced",replacedAt:new Date()}).where(inArray(courtyardSalesImportBatches.id,existing.map(x=>x.id)));}
 const p=parseSalesImport(req.file.buffer);const [batch]=await db.insert(courtyardSalesImportBatches).values({hotelId,reportYear,reportMonth,originalFilename:req.file.originalname,detectedDelimiter:p.delimiter,uploadedBy:req.salesUser.id,rowCount:p.rowsFound,acceptedRowCount:p.accepted.length,rejectedRowCount:p.rejected.length,duplicateRowCount:p.duplicateRowCount,fileChecksum:checksum,validationSummaryJson:{warnings:p.warnings,rejected:p.rejected.slice(0,100)}}).returning();if(p.accepted.length){await db.insert(courtyardSalesRawRows).values(p.accepted.map(r=>({importBatchId:batch.id,sourceRowNumber:r.sourceRowNumber,rawPayloadJson:r.raw,normalizedRowHash:r.normalizedRowHash})));await db.insert(courtyardSalesProduction).values(p.accepted.map(r=>({importBatchId:batch.id,hotelId,reportYear,reportMonth,globalUltimateAccountName:r.globalUltimateAccountName||null,highestLevelAccountId:r.highestLevelAccountId||null,accountName:r.accountName||null,accountId:r.accountId||null,accountType:r.accountType||null,marketCategory:r.marketCategory||null,marketSegment:r.marketSegment||null,rateProgramCode:r.rateProgramCode||null,rateProgram:r.rateProgram||null,bookingOffice:r.bookingOffice||null,roomNights:String(r.roomNights),roomRevenue:String(r.roomRevenue),roomAdr:String(r.roomAdr),totalRevenue:String(r.totalRevenue),totalAdr:String(r.totalAdr),averageLos:String(r.averageLos),fees:String(r.fees),taxes:String(r.taxes),addOns:String(r.addOns),sourceRowNumber:r.sourceRowNumber,normalizedAccountKey:r.normalizedAccountKey,normalizedRowHash:r.normalizedRowHash})));}const accounts=new Set(p.accepted.map(r=>r.normalizedAccountKey)).size;res.status(201).json({batchId:batch.id,label:periodLabel(reportYear,reportMonth),accounts,acceptedRows:p.accepted.length,rejectedRows:p.rejected.length,duplicateRows:p.duplicateRowCount,roomNights:p.accepted.reduce((s,r)=>s+r.roomNights,0),roomRevenue:p.accepted.reduce((s,r)=>s+r.roomRevenue,0)});}catch(e:any){if(e?.code==="LIMIT_FILE_SIZE")return res.status(413).json({error:"The file exceeds the 5 MB upload limit."});next(e)}});
 router.get("/dashboard",async(req:any,res,next)=>{try{const hotelId=String(req.query.hotelId||req.salesHotels[0]?.id||"");if(!hasHotel(req,hotelId))return res.status(403).json({error:"You do not have access to that property."});const batches=await db.select().from(courtyardSalesImportBatches).where(eq(courtyardSalesImportBatches.hotelId,hotelId)).orderBy(desc(courtyardSalesImportBatches.reportYear),desc(courtyardSalesImportBatches.reportMonth),desc(courtyardSalesImportBatches.createdAt));const active=batches.filter(b=>b.status==="completed");const batchIds=active.map(b=>b.id);const rows=batchIds.length?await db.select().from(courtyardSalesProduction).where(inArray(courtyardSalesProduction.importBatchId,batchIds)):[];const accounts=summarize(rows);const latest=accounts.length?Math.max(...accounts.map(a=>a.lastPeriod)):null;for(const a of accounts){const monthsSince=latest===null?0:latest-a.lastPeriod;a.monthsSinceLast=monthsSince;a.status=monthsSince>=RECOVERY_MONTHS?"Potential Recovery":"Active";a.recoveryPriority=recoveryPriority(a.roomRevenue,a.roomNights,monthsSince,a.history.length)}const periods=[...new Map(active.map(b=>[`${b.reportYear}-${b.reportMonth}`,{year:b.reportYear,month:b.reportMonth,label:periodLabel(b.reportYear,b.reportMonth)}])).values()];res.json({periods,latestPeriod:latest,accounts,imports:batches.map(b=>({...b,accounts:new Set(rows.filter(r=>r.importBatchId===b.id).map(r=>r.normalizedAccountKey)).size,roomNights:rows.filter(r=>r.importBatchId===b.id).reduce((s,r)=>s+n(r.roomNights),0),roomRevenue:rows.filter(r=>r.importBatchId===b.id).reduce((s,r)=>s+n(r.roomRevenue),0)}))});}catch(e){next(e)}});
 router.delete("/imports/:id",async(req:any,res,next)=>{try{if(!admin(req.salesUser))return res.status(403).json({error:"Manager access is required to delete imports."});const [batch]=await db.select().from(courtyardSalesImportBatches).where(eq(courtyardSalesImportBatches.id,req.params.id)).limit(1);if(!batch||!hasHotel(req,batch.hotelId))return res.status(404).json({error:"Import not found."});await db.delete(courtyardSalesImportBatches).where(eq(courtyardSalesImportBatches.id,batch.id));res.status(204).end();}catch(e){next(e)}});
 app.use("/api/courtyard/sales-intelligence",router);
}
