import { useState } from 'react';
import { ActivityIndicator, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { api } from '../services/api';
import { colors, radius, shadow, spacing, typography } from '../styles/theme';

type AIWeatherTranslatorCardProps = {
  origin?: string;
  destination?: string;
  metar?: string;
  taf?: string;
  pireps?: string;
  sigmet?: string;
};

export default function AIWeatherTranslatorCard({
  origin,
  destination,
  metar,
  taf,
  pireps,
  sigmet,
}: AIWeatherTranslatorCardProps) {
  const [summary, setSummary] = useState<string | null>(null);
  const [generatedAt, setGeneratedAt] = useState<string | null>(null);
  const [remainingUses, setRemainingUses] = useState<number | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const canGenerate = Boolean((metar && metar.trim()) || (taf && taf.trim()));

  const handleGenerate = async () => {
    if (!canGenerate || loading) return;
    setLoading(true);
    setError(null);

    try {
      const response = await api.post('/api/ai-tools/weather-summary', {
        origin,
        destination,
        metar,
        taf,
        pireps,
        sigmet,
      });

      setSummary(response.data?.summary || null);
      setGeneratedAt(response.data?.generatedAt || null);
      setRemainingUses(typeof response.data?.remainingUses === 'number' ? response.data.remainingUses : null);
    } catch (requestError: any) {
      setError(requestError?.response?.data?.error || requestError?.message || 'Unable to generate AI weather translation.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <View style={styles.card}>
      <View style={styles.header}>
        <View style={styles.titleRow}>
          <View style={styles.iconWrap}>
            <Ionicons name="sparkles-outline" size={16} color={colors.primary} />
          </View>
          <View style={{ flex: 1 }}>
            <Text style={styles.eyebrow}>AI WEATHER TRANSLATOR</Text>
            <Text style={styles.title}>Plain-English weather briefing for the current airport context.</Text>
          </View>
        </View>
        <TouchableOpacity
          style={[styles.button, !canGenerate && styles.buttonDisabled]}
          onPress={handleGenerate}
          disabled={!canGenerate || loading}
          activeOpacity={0.92}
        >
          {loading ? <ActivityIndicator color="#fff" /> : <Text style={styles.buttonText}>{summary ? 'Refresh' : 'Translate'}</Text>}
        </TouchableOpacity>
      </View>

      <Text style={styles.helper}>
        Uses the loaded METAR and TAF to generate a concise operational summary. Always verify with official sources before flight.
      </Text>

      {remainingUses !== null ? (
        <Text style={styles.meta}>
          {remainingUses > 0
            ? `${remainingUses} free AI use${remainingUses === 1 ? '' : 's'} remaining.`
            : 'Free AI usage limit reached. Pro Core is required for additional AI use.'}
        </Text>
      ) : null}

      {error ? <Text style={styles.error}>{error}</Text> : null}

      {!canGenerate ? (
        <Text style={styles.meta}>Load METAR or TAF data to enable the AI translator.</Text>
      ) : null}

      {summary ? (
        <View style={styles.summaryPanel}>
          <Text style={styles.summaryText}>{summary}</Text>
          <Text style={styles.meta}>
            Generated by AI{generatedAt ? ` · ${new Date(generatedAt).toLocaleTimeString()}` : ''}
          </Text>
        </View>
      ) : null}
    </View>
  );
}

const styles = StyleSheet.create({
  card: {
    marginTop: spacing.sm,
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    ...shadow.card,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  titleRow: {
    flex: 1,
    flexDirection: 'row',
    gap: spacing.sm,
  },
  iconWrap: {
    width: 32,
    height: 32,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primarySoft,
  },
  eyebrow: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1,
    color: colors.primary,
    textTransform: 'uppercase',
  },
  title: {
    ...typography.body,
    fontWeight: '700',
    color: colors.text,
    marginTop: 4,
  },
  helper: {
    ...typography.muted,
    marginTop: spacing.sm,
  },
  button: {
    minHeight: 40,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonDisabled: {
    opacity: 0.55,
  },
  buttonText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '800',
  },
  meta: {
    ...typography.muted,
    marginTop: spacing.sm,
  },
  error: {
    marginTop: spacing.sm,
    color: colors.danger,
    fontSize: 12,
    lineHeight: 18,
  },
  summaryPanel: {
    marginTop: spacing.sm,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceMuted,
    padding: spacing.md,
  },
  summaryText: {
    ...typography.body,
    color: colors.text,
  },
});
