import { useState } from "react";
import { Link } from "wouter";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import { trackEvent } from "@/lib/analytics";
import { apiUrl } from "@/lib/api";

type NotamTranslatorProps = {
  notams: string;
  airport?: string;
  route?: string;
};

export function NotamTranslator({
  notams,
  airport,
  route,
}: NotamTranslatorProps) {
  const [translation, setTranslation] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [generatedAt, setGeneratedAt] = useState<string | null>(null);
  const [remainingUses, setRemainingUses] = useState<number | null>(null);
  const { toast } = useToast();

  const handleGenerate = async () => {
    setIsLoading(true);
    setError(null);
    trackEvent("ai_notam_translate_generate", {
      notamLength: notams.length,
      hasAirport: !!airport,
      hasRoute: !!route,
    });
    try {
      const res = await fetch(apiUrl("/api/ai-tools/notam-translate"), {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify({ notams, airport, route }),
      });
      if (!res.ok) {
        const data = (await res.json()) as { error?: string };
        throw new Error(data.error ?? "Failed to translate NOTAMs");
      }
      const data = (await res.json()) as { translation: string; generatedAt: string; remainingUses?: number | null };
      setTranslation(data.translation);
      setGeneratedAt(data.generatedAt);
      setRemainingUses(typeof data.remainingUses === "number" ? data.remainingUses : null);
    } catch (err) {
      const message = err instanceof Error ? err.message : "Something went wrong";
      setError(message);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="space-y-3 rounded-lg border bg-muted/30 p-4">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex flex-wrap items-center gap-2">
          <span className="text-sm font-semibold">
            AI NOTAM Translator
          </span>
          <Badge variant="secondary" className="text-[10px]">
            Beta
          </Badge>
        </div>
        <Button
          size="sm"
          variant="outline"
          onClick={handleGenerate}
          disabled={isLoading || !notams.trim()}
          className="w-full sm:w-auto"
        >
          {isLoading ? "Translating..." : translation ? "Retranslate" : "Translate NOTAMs"}
        </Button>
      </div>

      {error && (
        <div className="text-xs text-destructive">{error}</div>
      )}

      {remainingUses !== null && !isLoading && (
        <div className="text-xs text-muted-foreground">
          {remainingUses > 0
            ? `${remainingUses} free AI use${remainingUses === 1 ? "" : "s"} remaining before RSF Premium is required.`
            : "Free AI usage limit reached. RSF Premium is required for additional AI use."}
        </div>
      )}

      {isLoading && (
        <div className="space-y-2 animate-pulse">
          <div className="h-3 w-full rounded bg-muted" />
          <div className="h-3 w-5/6 rounded bg-muted" />
          <div className="h-3 w-4/6 rounded bg-muted" />
        </div>
      )}

      {translation && !isLoading && (
        <div className="space-y-2">
          <div className="text-sm text-foreground whitespace-pre-wrap leading-relaxed">
            {translation}
          </div>
          <div className="flex flex-col gap-1 border-t pt-2 sm:flex-row sm:items-center sm:justify-between">
            <span className="text-[10px] text-muted-foreground">
              Generated by AI - NOTAMs may affect flight legality - always verify with official sources
            </span>
            {generatedAt && (
              <span className="text-[10px] text-muted-foreground">
                {new Date(generatedAt).toLocaleTimeString()}
              </span>
            )}
          </div>
          <Button
            size="sm"
            variant="ghost"
            className="h-7 w-full text-xs sm:w-auto"
            onClick={async () => {
              await navigator.clipboard.writeText(translation);
              toast({ title: "Translation copied" });
            }}
          >
            Copy translation
          </Button>
        </div>
      )}

      {!notams.trim() && (
        <div className="text-xs text-muted-foreground">
          Load NOTAMs above to enable translation.
        </div>
      )}

      {(remainingUses === 0 || error?.includes("RSF Premium")) && (
        <Button asChild size="sm" className="w-full sm:w-auto">
          <Link href="/logbook/pro">Upgrade to RSF Premium</Link>
        </Button>
      )}
    </div>
  );
}

export default NotamTranslator;
