import { useState } from "react";
import { Link } from "wouter";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import { trackEvent } from "@/lib/analytics";
import { apiUrl } from "@/lib/api";

type WeatherBriefingSummarizerProps = {
  metar?: string;
  taf?: string;
  pireps?: string;
  sigmet?: string;
  origin?: string;
  destination?: string;
};

export function WeatherBriefingSummarizer({
  metar,
  taf,
  pireps,
  sigmet,
  origin,
  destination,
}: WeatherBriefingSummarizerProps) {
  const [summary, setSummary] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [generatedAt, setGeneratedAt] = useState<string | null>(null);
  const [remainingUses, setRemainingUses] = useState<number | null>(null);
  const { toast } = useToast();

  const handleGenerate = async () => {
    setIsLoading(true);
    setError(null);
    trackEvent("ai_weather_summary_generate", {
      hasMetar: !!metar,
      hasTaf: !!taf,
      hasPireps: !!pireps,
      hasSigmet: !!sigmet,
    });
    try {
      const res = await fetch(apiUrl("/api/ai-tools/weather-summary"), {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify({
          metar,
          taf,
          pireps,
          sigmet,
          origin,
          destination,
        }),
      });
      if (!res.ok) {
        const data = (await res.json()) as { error?: string };
        throw new Error(data.error ?? "Failed to generate summary");
      }
      const data = (await res.json()) as { summary: string; generatedAt: string; remainingUses?: number | null };
      setSummary(data.summary);
      setGeneratedAt(data.generatedAt);
      setRemainingUses(typeof data.remainingUses === "number" ? data.remainingUses : null);
    } catch (err) {
      const message = err instanceof Error ? err.message : "Something went wrong";
      setError(message);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="space-y-3 rounded-lg border bg-muted/30 p-4">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex flex-wrap items-center gap-2">
          <span className="text-sm font-semibold">
            AI Weather Summary
          </span>
          <Badge variant="secondary" className="text-[10px]">
            Beta
          </Badge>
        </div>
        <Button
          size="sm"
          variant="outline"
          onClick={handleGenerate}
          disabled={isLoading || (!metar && !taf)}
          className="w-full sm:w-auto"
        >
          {isLoading ? "Summarizing..." : summary
            ? "Regenerate" : "Summarize weather"}
        </Button>
      </div>

      {error && (
        <div className="text-xs text-destructive">{error}</div>
      )}

      {remainingUses !== null && !isLoading && (
        <div className="text-xs text-muted-foreground">
          {remainingUses > 0
            ? `${remainingUses} free AI use${remainingUses === 1 ? "" : "s"} remaining before RSF Premium is required.`
            : "Free AI usage limit reached. RSF Premium is required for additional AI use."}
        </div>
      )}

      {isLoading && (
        <div className="space-y-2 animate-pulse">
          <div className="h-3 w-full rounded bg-muted" />
          <div className="h-3 w-5/6 rounded bg-muted" />
          <div className="h-3 w-4/6 rounded bg-muted" />
        </div>
      )}

      {summary && !isLoading && (
        <div className="space-y-2">
          <div className="text-sm text-foreground whitespace-pre-wrap leading-relaxed">
            {summary}
          </div>
          <div className="flex flex-col gap-1 border-t pt-2 sm:flex-row sm:items-center sm:justify-between">
            <span className="text-[10px] text-muted-foreground">
              Generated by AI - Always verify with official sources
            </span>
            {generatedAt && (
              <span className="text-[10px] text-muted-foreground">
                {new Date(generatedAt).toLocaleTimeString()}
              </span>
            )}
          </div>
          <Button
            size="sm"
            variant="ghost"
            className="h-7 w-full text-xs sm:w-auto"
            onClick={async () => {
              await navigator.clipboard.writeText(summary);
              toast({ title: "Summary copied" });
            }}
          >
            Copy summary
          </Button>
        </div>
      )}

      {!metar && !taf && (
        <div className="text-xs text-muted-foreground">
          Load weather data above to enable AI summary.
        </div>
      )}

      {(remainingUses === 0 || error?.includes("RSF Premium")) && (
        <Button asChild size="sm" className="w-full sm:w-auto">
          <Link href="/logbook/pro">Upgrade to RSF Premium</Link>
        </Button>
      )}
    </div>
  );
}

export default WeatherBriefingSummarizer;
