import { useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import { useAuth } from "@/hooks/useAuth";
import { trackEvent } from "@/lib/analytics";
import { apiUrl } from "@/lib/api";

type WeatherBriefingSummarizerProps = {
  metar?: string;
  taf?: string;
  pireps?: string;
  sigmet?: string;
  origin?: string;
  destination?: string;
};

export function WeatherBriefingSummarizer({
  metar,
  taf,
  pireps,
  sigmet,
  origin,
  destination,
}: WeatherBriefingSummarizerProps) {
  const [summary, setSummary] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [generatedAt, setGeneratedAt] = useState<string | null>(null);
  const [authRequired, setAuthRequired] = useState(false);
  const { toast } = useToast();
  const { isAuthenticated } = useAuth();

  const handleGenerate = async () => {
    setIsLoading(true);
    setError(null);
    setAuthRequired(false);
    trackEvent("ai_weather_summary_generate", {
      hasMetar: !!metar,
      hasTaf: !!taf,
      hasPireps: !!pireps,
      hasSigmet: !!sigmet,
    });
    try {
      const res = await fetch(apiUrl("/api/ai-tools/weather-summary"), {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify({
          metar,
          taf,
          pireps,
          sigmet,
          origin,
          destination,
        }),
      });
      if (res.status === 401) {
        setAuthRequired(true);
        setSummary(null);
        setGeneratedAt(null);
        return;
      }
      if (!res.ok) {
        const data = (await res.json()) as { error?: string };
        throw new Error(data.error ?? "Failed to generate summary");
      }
      const data = (await res.json()) as { summary: string; generatedAt: string };
      setSummary(data.summary);
      setGeneratedAt(data.generatedAt);
    } catch (err) {
      const message = err instanceof Error ? err.message : "Something went wrong";
      setError(message);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="rounded-lg border bg-muted/30 p-4 space-y-3">
      <div className="flex items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <span className="text-sm font-semibold">
            AI Weather Summary
          </span>
          <Badge variant="secondary" className="text-[10px]">
            Beta
          </Badge>
        </div>
        {authRequired || !isAuthenticated ? (
          <span className="text-xs text-muted-foreground">Sign in to use AI features</span>
        ) : (
          <Button
            size="sm"
            variant="outline"
            onClick={handleGenerate}
            disabled={isLoading || (!metar && !taf)}
          >
            {isLoading ? "Summarizing..." : summary
              ? "Regenerate" : "Summarize weather"}
          </Button>
        )}
      </div>

      {error && (
        <div className="text-xs text-destructive">{error}</div>
      )}

      {isLoading && (
        <div className="space-y-2 animate-pulse">
          <div className="h-3 w-full rounded bg-muted" />
          <div className="h-3 w-5/6 rounded bg-muted" />
          <div className="h-3 w-4/6 rounded bg-muted" />
        </div>
      )}

      {summary && !isLoading && (
        <div className="space-y-2">
          <div className="text-sm text-foreground whitespace-pre-wrap leading-relaxed">
            {summary}
          </div>
          <div className="flex items-center justify-between border-t pt-2">
            <span className="text-[10px] text-muted-foreground">
              Generated by AI · Always verify with official sources
            </span>
            {generatedAt && (
              <span className="text-[10px] text-muted-foreground">
                {new Date(generatedAt).toLocaleTimeString()}
              </span>
            )}
          </div>
          <Button
            size="sm"
            variant="ghost"
            className="h-7 text-xs"
            onClick={async () => {
              await navigator.clipboard.writeText(summary);
              toast({ title: "Summary copied" });
            }}
          >
            Copy summary
          </Button>
        </div>
      )}

      {!metar && !taf && (
        <div className="text-xs text-muted-foreground">
          Load weather data above to enable AI summary.
        </div>
      )}
    </div>
  );
}

export default WeatherBriefingSummarizer;
